export const PROVIDERS = {
  google_translate_v2: {
    label: "Google Translate v2",
    group: "Stable / Recommended",
    hint: "Primary recommended provider. Requires a Google Translate v2 API key.",
    fields: ["api_key"],
    status: "Stable machine-translation provider.",
  },
  google_cloud_translation_v3: {
    label: "Google Cloud Translation - Advanced (v3)",
    group: "Stable / Recommended",
    hint: "Official Google Cloud Translation - Advanced REST API. Requires project ID and OAuth access token, not a v2 API key.",
    fields: ["api_key", "endpoint", "region", "model"],
    apiKeyLabel: { en: "Access token", ru: "Access token" },
    apiKeyPlaceholder: "OAuth access token",
    endpointLabel: { en: "Project ID", ru: "Project ID" },
    endpointPlaceholder: "my-gcp-project",
    regionLabel: { en: "Location", ru: "Location" },
    regionPlaceholder: "global",
    modelLabel: { en: "Model (optional)", ru: "Model (опционально)" },
    modelPlaceholder: "general/nmt or general/translation-llm",
    status: "Stable cloud MT provider. Uses the Advanced v3 endpoint.",
  },
  google_gas_url: {
    label: "Google GAS URL",
    group: "Experimental / Emergency",
    hint: "Experimental best-effort Google Apps Script bridge. Reliability depends on your script and deployment.",
    fields: ["gas_url"],
    status: "Experimental provider. Use only if you control the GAS endpoint.",
  },
  google_web: {
    label: "Google Web",
    group: "Experimental / Emergency",
    hint: "Experimental unofficial Google web endpoint. Best-effort only and may break anytime.",
    fields: [],
    status: "Experimental provider. Not recommended as the primary path.",
  },
  azure_translator: {
    label: "Azure Translator",
    group: "Stable / Recommended",
    hint: "Stable provider. Requires Azure Translator API key and usually a region.",
    fields: ["api_key", "endpoint", "region"],
    endpointPlaceholder: "https://api.cognitive.microsofttranslator.com",
    status: "Stable machine-translation provider.",
  },
  deepl: {
    label: "DeepL",
    group: "Classic MT",
    hint: "Requires a DeepL API key. API URL can stay at the default value.",
    fields: ["api_key", "api_url"],
    apiUrlPlaceholder: "https://api-free.deepl.com/v2/translate",
    status: "Classic MT provider.",
  },
  libretranslate: {
    label: "LibreTranslate",
    group: "Classic MT",
    hint: "Use your own LibreTranslate server or a managed endpoint. API key is optional depending on the server.",
    fields: ["api_key", "api_url"],
    apiUrlPlaceholder: "https://libretranslate.com/translate",
    status: "Classic MT provider. Reliability depends on the endpoint you choose.",
  },
  openai: {
    label: "OpenAI",
    group: "Flexible LLM",
    hint: "Flexible LLM subtitle translation. Requires API key, model, and uses the built-in subtitle prompt unless overridden.",
    fields: ["api_key", "base_url", "model", "custom_prompt"],
    baseUrlPlaceholder: "https://api.openai.com/v1",
    status: "Model-quality-dependent LLM provider.",
  },
  openrouter: {
    label: "OpenRouter",
    group: "Flexible LLM",
    hint: "OpenAI-compatible routing layer. Requires API key and model.",
    fields: ["api_key", "base_url", "model", "custom_prompt"],
    baseUrlPlaceholder: "https://openrouter.ai/api/v1",
    status: "Model-quality-dependent LLM provider.",
  },
  lm_studio: {
    label: "LM Studio",
    group: "Local LLM",
    hint: "Local OpenAI-compatible server. Quality depends on your locally loaded model.",
    fields: ["base_url", "model", "custom_prompt"],
    baseUrlPlaceholder: "http://127.0.0.1:1234/v1",
    status: "Local model-quality-dependent provider.",
  },
  ollama: {
    label: "Ollama",
    group: "Local LLM",
    hint: "Local OpenAI-compatible endpoint. Quality depends on your local model.",
    fields: ["base_url", "model", "custom_prompt"],
    baseUrlPlaceholder: "http://127.0.0.1:11434/v1",
    status: "Local model-quality-dependent provider.",
  },
  public_libretranslate_mirror: {
    label: "Public LibreTranslate Mirror",
    group: "Experimental / Emergency",
    hint: "Experimental public mirror. Availability can change without notice.",
    fields: ["api_url"],
    apiUrlPlaceholder: "https://translate.fedilab.app/translate",
    status: "Experimental public provider. Reliability is not guaranteed.",
  },
  free_web_translate: {
    label: "Free Web Translate",
    group: "Experimental / Emergency",
    hint: "Experimental no-key web provider. Best-effort only.",
    fields: [],
    status: "Experimental public provider. Behavior may change without notice.",
  },
};

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "ja", label: "Japanese" },
  { code: "de", label: "German" },
  { code: "es", label: "Spanish" },
  { code: "fr", label: "French" },
  { code: "it", label: "Italian" },
  { code: "ko", label: "Korean" },
  { code: "pt", label: "Portuguese" },
  { code: "ru", label: "Russian" },
  { code: "zh-cn", label: "Chinese (Simplified)" },
];

export const BROWSER_RECOGNITION_LANGUAGES = [
  { code: "ru-RU", label: "Russian (ru-RU)" },
  { code: "en-US", label: "English (en-US)" },
  { code: "de-DE", label: "German (de-DE)" },
  { code: "es-ES", label: "Spanish (es-ES)" },
  { code: "fr-FR", label: "French (fr-FR)" },
  { code: "it-IT", label: "Italian (it-IT)" },
  { code: "ja-JP", label: "Japanese (ja-JP)" },
  { code: "ko-KR", label: "Korean (ko-KR)" },
  { code: "pt-BR", label: "Portuguese (pt-BR)" },
  { code: "uk-UA", label: "Ukrainian (uk-UA)" },
  { code: "zh-CN", label: "Chinese Simplified (zh-CN)" },
];

export const SIMPLE_TUNING_OPTIONS = {
  appearance: [
    { label: "Steadier", partial_emit_interval_ms: 560, min_speech_ms: 260 },
    { label: "Calm", partial_emit_interval_ms: 500, min_speech_ms: 220 },
    { label: "Balanced", partial_emit_interval_ms: 450, min_speech_ms: 180 },
    { label: "Quick", partial_emit_interval_ms: 360, min_speech_ms: 140 },
    { label: "Fast", partial_emit_interval_ms: 280, min_speech_ms: 100 },
  ],
  finish: [
    { label: "Wait Longer", silence_hold_ms: 260, pause_to_finalize_ms: 650 },
    { label: "Relaxed", silence_hold_ms: 220, pause_to_finalize_ms: 500 },
    { label: "Balanced", silence_hold_ms: 180, pause_to_finalize_ms: 350 },
    { label: "Quick", silence_hold_ms: 150, pause_to_finalize_ms: 300 },
    { label: "Fast", silence_hold_ms: 120, pause_to_finalize_ms: 260 },
  ],
  stability: [
    { label: "Live", partial_min_delta_chars: 4, partial_coalescing_ms: 80 },
    { label: "Responsive", partial_min_delta_chars: 8, partial_coalescing_ms: 120 },
    { label: "Balanced", partial_min_delta_chars: 12, partial_coalescing_ms: 160 },
    { label: "Steady", partial_min_delta_chars: 15, partial_coalescing_ms: 240 },
    { label: "Very Steady", partial_min_delta_chars: 18, partial_coalescing_ms: 320 },
  ],
};

export const PROVIDER_GROUP_KEYS = {
  "Stable / Recommended": { en: "Stable / Recommended", ru: "Стабильно / рекомендуется" },
  "Experimental / Emergency": { en: "Experimental / Emergency", ru: "Экспериментально / запасной вариант" },
  "Classic MT": { en: "Classic MT", ru: "Классический MT" },
  "Flexible LLM": { en: "Flexible LLM", ru: "Гибкая LLM" },
  "Local LLM": { en: "Local LLM", ru: "Локальная LLM" },
};

export const LANGUAGE_LABELS = {
  en: { en: "English", ru: "Английский" },
  ja: { en: "Japanese", ru: "Японский" },
  de: { en: "German", ru: "Немецкий" },
  es: { en: "Spanish", ru: "Испанский" },
  fr: { en: "French", ru: "Французский" },
  it: { en: "Italian", ru: "Итальянский" },
  ko: { en: "Korean", ru: "Корейский" },
  pt: { en: "Portuguese", ru: "Португальский" },
  ru: { en: "Russian", ru: "Русский" },
  "zh-cn": { en: "Chinese (Simplified)", ru: "Китайский (упрощённый)" },
};

export const BROWSER_RECOGNITION_LABELS = {
  "ru-RU": { en: "Russian (ru-RU)", ru: "Русский (ru-RU)" },
  "en-US": { en: "English (en-US)", ru: "Английский (en-US)" },
  "de-DE": { en: "German (de-DE)", ru: "Немецкий (de-DE)" },
  "es-ES": { en: "Spanish (es-ES)", ru: "Испанский (es-ES)" },
  "fr-FR": { en: "French (fr-FR)", ru: "Французский (fr-FR)" },
  "it-IT": { en: "Italian (it-IT)", ru: "Итальянский (it-IT)" },
  "ja-JP": { en: "Japanese (ja-JP)", ru: "Японский (ja-JP)" },
  "ko-KR": { en: "Korean (ko-KR)", ru: "Корейский (ko-KR)" },
  "pt-BR": { en: "Portuguese (pt-BR)", ru: "Португальский (pt-BR)" },
  "uk-UA": { en: "Ukrainian (uk-UA)", ru: "Украинский (uk-UA)" },
  "zh-CN": { en: "Chinese Simplified (zh-CN)", ru: "Китайский упрощённый (zh-CN)" },
};

export const SIMPLE_TUNING_LABELS = {
  appearance: {
    Steadier: { en: "Steadier", ru: "Спокойнее" },
    Calm: { en: "Calm", ru: "Мягко" },
    Balanced: { en: "Balanced", ru: "Баланс" },
    Quick: { en: "Quick", ru: "Быстро" },
    Fast: { en: "Fast", ru: "Очень быстро" },
  },
  finish: {
    "Wait Longer": { en: "Wait Longer", ru: "Подождать дольше" },
    Relaxed: { en: "Relaxed", ru: "Спокойно" },
    Balanced: { en: "Balanced", ru: "Баланс" },
    Quick: { en: "Quick", ru: "Быстро" },
    Fast: { en: "Fast", ru: "Очень быстро" },
  },
  stability: {
    Live: { en: "Live", ru: "Живее" },
    Responsive: { en: "Responsive", ru: "Отзывчиво" },
    Balanced: { en: "Balanced", ru: "Баланс" },
    Steady: { en: "Steady", ru: "Спокойно" },
    "Very Steady": { en: "Very Steady", ru: "Очень спокойно" },
  },
};
