from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class SchemaModel(BaseModel):
    model_config = ConfigDict(extra="ignore")


class BrowserAsrDiagnostics(SchemaModel):
    worker_connected: bool = False
    browser_mode: str | None = None
    start_mode: str | None = None
    experimental: bool = False
    session_id: str | None = None
    generation_id: int = 0
    client_segment_id: str | None = None
    desired_running: bool | None = None
    pending_start: bool | None = None
    recognition_running: bool | None = None
    recognition_state: str | None = None
    supervisor_state: str | None = None
    effective_continuous_mode: str | None = None
    recognition_continuous: bool | None = None
    websocket_ready: bool | None = None
    audio_track_enabled: bool | None = None
    audio_track_live: bool | None = None
    audio_track_kind: str | None = None
    audio_track_ready_state: str | None = None
    audio_track_muted: bool | None = None
    audio_track_reused: bool | None = None
    audio_track_reopen_count: int = 0
    audio_track_start_attempts: int = 0
    audio_track_start_failures: int = 0
    fallback_to_default_start: bool | None = None
    fallback_used: bool | None = None
    last_start_error: str | None = None
    last_audio_track_error: str | None = None
    forced_final: bool | None = None
    provider_name: str | None = None
    active_recognition: bool | None = None
    active_media_stream: bool | None = None
    last_partial_text: str | None = None
    last_final_text: str | None = None
    last_result_index: int | None = None
    last_result_at_ms: int | None = None
    last_partial_at_utc: str | None = None
    last_final_at_utc: str | None = None
    last_partial_age_ms: int | None = None
    last_final_age_ms: int | None = None
    last_session_started_at_ms: int | None = None
    last_session_ended_at_ms: int | None = None
    browser_session_age_ms: int | None = None
    browser_cycle_pending: bool | None = None
    browser_cycle_count: int = 0
    browser_minimum_reconnect_suppressed_count: int = 0
    browser_forced_final_on_interruption_count: int = 0
    last_error: str | None = None
    error_type: str | None = None
    rearm_count: int = 0
    restart_count: int = 0
    no_speech_count: int = 0
    network_error_count: int = 0
    watchdog_rearm_count: int = 0
    duplicate_partial_suppressed: int = 0
    duplicate_final_suppressed: int = 0
    late_forced_final_suppressed: int = 0
    degraded_reason: str | None = None
    visibility_state: str | None = None
    mic_track_ready_state: str | None = None
    mic_track_muted: bool | None = None
    mic_rms: float | None = None
    mic_active_recent_ms: int | None = None
    last_mic_activity_at: int | None = None
    get_user_media_count: int = 0
    get_user_media_last_error: str | None = None
    mic_stream_active: bool | None = None
    media_tracks_stopped_count: int = 0
    media_track_leak_guard_count: int = 0
    last_status_reason: str | None = None
    last_rearm_delay_ms: int | None = None
    stopping_since_ms: int | None = None
    last_seen_at_ms: int | None = None
    browser_worker_last_seen_age_ms: int | None = None
    stale_worker_events_ignored: int = 0


class AsrDiagnostics(SchemaModel):
    mode: str | None = None
    provider_preference: str | None = None
    effective_provider: str | None = None
    provider: str
    provider_label: str | None = None
    provider_kind: str | None = None
    provider_mode_kind: Literal["local_ai", "browser_speech", "unknown"] = "unknown"
    uses_browser_worker: bool = False
    uses_backend_audio_capture: bool = False
    true_streaming: bool = False
    requested_provider: str | None = None
    requested_device_policy: str | None = None
    requested_device: str | None = None
    model_load_mode: str | None = None
    model_repo: str | None = None
    model_revision: str | None = None
    model_path: str | None = None
    model_integrity_state: str | None = None
    model_loaded: bool = False
    model_manifest: dict[str, object] | None = None
    supports_gpu: bool = False
    supports_partials: bool = False
    supports_streaming: bool = False
    gpu_requested: bool = False
    gpu_available: bool = False
    cuda_available: bool = False
    torch_version: str | None = None
    torch_built_with_cuda: bool = False
    torch_cuda_is_available: bool = False
    torch_cuda_version: str | None = None
    torch_device_count: int = 0
    first_gpu_name: str | None = None
    python_executable: str | None = None
    venv_path: str | None = None
    degraded_mode: bool = False
    fallback_reason: str | None = None
    cpu_fallback_reason: str | None = None
    selected_device: str | None = None
    device_active: str | None = None
    selected_execution_provider: str | None = None
    partials_supported: bool = False
    sample_rate: int | None = None
    audio_frame_duration_ms: int | None = None
    vad_mode: int | None = None
    vad_partial_interval_ms: int | None = None
    vad_min_speech_ms: int | None = None
    vad_first_partial_min_speech_ms: int | None = None
    vad_silence_padding_ms: int | None = None
    vad_finalization_hold_ms: int | None = None
    vad_max_segment_ms: int | None = None
    vad_energy_gate_enabled: bool = False
    vad_min_rms_for_recognition: float | None = None
    vad_min_voiced_ratio: float | None = None
    realtime_chunk_window_ms: int | None = None
    realtime_chunk_overlap_ms: int | None = None
    partial_min_delta_chars: int | None = None
    partial_coalescing_ms: int | None = None
    active_latency_preset: str | None = None
    recognition_noise_reduction_enabled: bool = False
    rnnoise_strength: int = 0
    rnnoise_available: bool = False
    rnnoise_active: bool = False
    rnnoise_backend: str | None = None
    rnnoise_uses_resample: bool = False
    rnnoise_input_sample_rate: int | None = None
    rnnoise_processing_sample_rate: int | None = None
    rnnoise_frame_size_samples: int | None = None
    rnnoise_message: str | None = None
    message: str | None = None
    runtime_initialized: bool = False
    provider_state: str | None = None
    provider_phase: str | None = None
    provider_message: str | None = None
    provider_error_kind: str | None = None
    provider_last_error: str | None = None
    stream_generation: int = 0
    desired_running: bool | None = None
    upstream_connected: bool | None = None
    downstream_connected: bool | None = None
    reconnect_count: int = 0
    no_results_timeout_count: int = 0
    last_no_results_timeout_at_ms: int | None = None
    audio_sent_without_results_ms: int | None = None
    audio_queue_depth: int = 0
    audio_capture_active: bool | None = None
    audio_capture_device_label: str | None = None
    audio_chunks_received_from_capture: int = 0
    audio_chunks_enqueued: int = 0
    audio_chunks_sent: int = 0
    audio_chunks_dropped: int = 0
    bytes_sent: int = 0
    audio_input_rms: float | None = None
    audio_input_peak: float | None = None
    last_audio_chunk_age_ms: int | None = None
    last_audio_sent_age_ms: int | None = None
    last_result_age_ms: int | None = None
    stale_results_ignored: int = 0
    downstream_messages_received: int = 0
    downstream_parse_errors: int = 0
    downstream_empty_results: int = 0
    partials_received: int = 0
    finals_received: int = 0
    last_partial_text_len: int | None = None
    last_final_text_len: int | None = None
    duplicate_partials_suppressed: int = 0
    duplicate_finals_suppressed: int = 0
    last_error: str | None = None
    last_error_kind: str | None = None
    last_partial_age_ms: int | None = None
    last_final_age_ms: int | None = None
    connect_timeout_ms: int | None = None
    send_timeout_ms: int | None = None
    recv_timeout_ms: int | None = None
    max_queue_depth: int | None = None
    forced_final_on_interruption_count: int = 0
    minimum_reconnect_suppressed_count: int = 0
    result_index_last: int | None = None
    parakeet_generation: int | None = None
    asr_queue_depth: int = 0
    asr_queue_max_size: int | None = None
    asr_partial_jobs_dropped: int = 0
    asr_stale_results_ignored: int = 0
    in_flight_transcribe_count: int = 0
    partial_jobs_coalesced: int = 0
    stale_partial_jobs_dropped: int = 0
    finals_prioritized_count: int = 0
    vad_to_asr_enqueue_ms: float | None = None
    asr_queue_wait_ms: float | None = None
    asr_transcribe_ms: float | None = None
    asr_result_to_router_ms: float | None = None
    asr_result_to_dashboard_ms: float | None = None
    first_transcribe_warmup_ms: float | None = None
    inference_mode_enabled: bool | None = None
    gpu_memory_allocated_mb: float | None = None
    gpu_memory_reserved_mb: float | None = None
    gpu_peak_memory_allocated_mb: float | None = None
    cuda_cache_cleared_count: int = 0
    stream_states_count: int | None = None
    stop_flush_count: int = 0
    browser_worker: BrowserAsrDiagnostics | None = None


class AsrRuntimeStatus(SchemaModel):
    active_mode: str = "local"
    provider_preference: str | None = None
    effective_provider: str | None = None
    provider: str | None = None
    provider_label: str | None = None
    provider_kind: str | None = None
    uses_browser_worker: bool = False
    uses_backend_audio_capture: bool = False
    provider_phase: str | None = None
    provider_message: str | None = None
    provider_error_kind: str | None = None
    provider_last_error: str | None = None
    ready: bool = False
    true_streaming: bool = False
    supports_partials: bool = False
    degraded_mode: bool = False
    fallback_reason: str | None = None
    diagnostics: AsrDiagnostics | None = None
